### DISCUSSION TITLE
Dockerizing instances?

### DISCUSSION THREAD

**Discussion by benallfree** [pockethost/pockethost#269] [Q&A]
From https://github.com/benallfree/pockethost/discussions/223#discussioncomment-6648823 and other Docker-related discussion, I wanted to open a community discussion about Dockerizing pocketbase instances.

Considerations:

* Ability to run any pocketbase version from a single container
* Ability to run Deno from the container
* Limiting resources and file system access
* Ability to proxy both HTTP and FTP from the host
* Startup time

These are the major must-haves in any Dockerized scenario, and is why we moved away from it in the first place. The alternative is to use `cpulimit` and other linux-based tools and create separate linux users for each pockethost instance so access can be properly controlled. 

@cheskoxd Is this something you'd like to take on?

**Comment by cheskoxd** [comment]
I can start gathering some info and testing on my end

brainstorming:

The proxy for http and ftp can be done with nginx
maybe something like this
```
server {
    listen 80;
    server_name ~^(?<instance>[^.]+)\.your\.domain\.com$;

    location / {
        proxy_pass http://pocketbase_$instance;
    }

    location /ftp/ {
        proxy_pass ftp://pocketbase_$instance;
        proxy_set_header Authorization "Basic base64_username_password";  # Replace with FTP authentication if required
    }
}

```
So it will get the instance based on the subdomain.

For creating new instances we can run 
```
docker service create \
  --env INSTANCE_NAME=my_custom_instance \
  --name my_pocketbase_instance \
  your_pocketbase_image:latest

```

And for getting the logs 
```
docker service logs --filter "container=<container_id_or_name>" my_pocketbase_instance

```

Then the docker-compose can be something like (same compose sent to the other thread )
```
version: '3.8'
services:
  pocketbase:
    image: your_pocketbase_image:latest
    environment:
      - POCKETBASE_VERSION=1.0.0  # Set the desired version for PocketBase
      - DENO_VERSION=2.5.1  # Set the desired version for Deno
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Maximum 50% of a CPU core per instance
          memory: '512M'  # Maximum 512MB of memory per instance
        reservations:
          cpus: '0.1'  # Minimum 10% of a CPU core per instance
          memory: '128M'  # Minimum 
```

I'm sending this info to get more feedback, and also I'm not close to my laptop so I'm on my phone trying to brainstorm
